/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_n1_dtvjni_MainActivity */

#ifndef _Included_com_example_n1_dtvjni_MainActivity
#define _Included_com_example_n1_dtvjni_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_n1_dtvjni_MainActivity
 * Method:    switch_to
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_n1_dtvjni_MainActivity_switch_1to
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_n1_dtvjni_MainActivity
 * Method:    power_control
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_n1_dtvjni_MainActivity_power_1control
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
